AllCops:
  SuggestExtensions: false

Style/HashSyntax:
  EnforcedStyle: no_mixed_keys
  EnforcedShorthandSyntax: never

Metrics/MethodLength:
  Max: 32

Style/GlobalVars:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - "server_tests/*"
    - "client_tests/*"

Metrics/ClassLength:
  Exclude:
    - "server_tests/*"
    - "client_tests/*"

Style/ClassVars:
  Exclude:
    - "server_tests/*"
    - "client_tests/*"
