AllCops:
  SuggestExtensions: false
  NewCops: enable
  StringLiteralsFrozenByDefault: true

Style/HashSyntax:
  EnforcedStyle: no_mixed_keys
  EnforcedShorthandSyntax: never

Metrics/MethodLength:
  Max: 32

Style/GlobalVars:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
  EnforcedStyle: never

Metrics/AbcSize:
  Exclude:
    - "server_tests/*"
    - "client_tests/*"

Metrics/ClassLength:
  Exclude:
    - "server_tests/*"
    - "client_tests/*"

Style/ClassVars:
  Exclude:
    - "server_tests/*"
    - "client_tests/*"
